using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace DbExport.Schema;

#region QueryOptions enum

/// <summary>
/// Specifies options for customizing the behavior of query generation in database operations.
/// These options determine how tables and columns are processed and formatted during SQL generation.
/// </summary>
[Flags]
public enum QueryOptions
{
    /// <summary>
    /// Indicates that no query options are applied. This is the default value, meaning
    /// that all applicable table columns and default behaviors are included during
    /// SQL generation without exclusions or modifications.
    /// </summary>
    None = 0,

    /// <summary>
    /// Indicates that identity columns are excluded during query generation.
    /// This option prevents the inclusion of columns that are marked as identity fields,
    /// typically used for automatically generated values in database tables.
    /// </summary>
    SkipIdentity = 1,

    /// <summary>
    /// Specifies that computed columns are excluded during query generation.
    /// This option removes columns with calculated values, such as those defined
    /// with SQL expressions, from the generated SQL statement.
    /// </summary>
    SkipComputed = 2,

    /// <summary>
    /// Indicates that columns marked with the RowVersion property should be excluded
    /// from the query generation process. This option is used to prevent
    /// inclusion of RowVersion columns, which are typically used for concurrency
    /// tracking and may not be necessary in certain queries or export scenarios.
    /// </summary>
    SkipRowVersion = 4,

    /// <summary>
    /// Represents a combination of query options that excludes identity, computed, and row version columns
    /// during SQL generation. This option is used to skip all columns that are automatically generated by
    /// the database, ensuring they are omitted from the resulting query.
    /// </summary>
    SkipGenerated = SkipIdentity | SkipComputed | SkipRowVersion,

    /// <summary>
    /// Specifies that fully qualified table names, including schema names, should be used
    /// during SQL generation. This ensures that table references are explicit, which can help
    /// avoid ambiguities when working with multiple schemas or databases.
    /// </summary>
    QualifyTableName = 8,

    /// <summary>
    /// Represents a combination of all available query options. This includes skipping
    /// identity, computed, and row version columns during query generation, as well as
    /// qualifying table names with schema information, ensuring comprehensive customization
    /// of the query output.
    /// </summary>
    All = SkipGenerated | QualifyTableName
}

#endregion

/// <summary>
/// Contains extension methods for performing various database operations on a <see cref="Table"/> object.
/// These operations include generating SQL statements (SELECT, INSERT, UPDATE, DELETE),
/// executing queries, and managing batch operations.
/// </summary>
public static class TableExtensions
{
    #region SQL generation methods

    /// <summary>
    /// Generates a SQL SELECT statement for the specified table based on the provided query options.
    /// </summary>
    /// <param name="table">The table for which the SELECT statement will be generated.</param>
    /// <param name="options">The query options that define which columns to include and how the table name should be qualified.</param>
    /// <returns>A string containing the generated SQL SELECT statement.</returns>
    public static string GenerateSelect(this Table table, QueryOptions options)
    {
        StringBuilder queryBuilder = new("SELECT ");
        var providerName = table.Database.ProviderName;

        foreach (var column in table.Columns.Where(c => c.IsMatch(options)))
            queryBuilder.Append(Utility.Escape(column.Name, providerName)).Append(", ");

        queryBuilder.Length -= 2;
        queryBuilder.Append(" FROM ");
        queryBuilder.AppendNameOf(table, providerName, options);

        return queryBuilder.ToString();
    }

    /// <summary>
    /// Generates a SQL SELECT statement for the specified table, filtering results based on the given key
    /// and applying the provided query options.
    /// </summary>
    /// <param name="table">The table for which the SELECT statement will be generated.</param>
    /// <param name="key">The key defining the filter criteria for the SELECT statement.</param>
    /// <param name="options">The query options that specify how the statement should be generated, including conditions and table name qualification.</param>
    /// <returns>A string containing the generated SQL SELECT statement with the applied key filter.</returns>
    public static string GenerateSelect(this Table table, Key key, QueryOptions options)
    {
        Trace.Assert(table == key.Table); // The key should belong to the table

        StringBuilder queryBuilder = new();
        queryBuilder.Append(table.GenerateSelect(options));
        queryBuilder.AppendFilterBy(key, table.Database.ProviderName);

        return queryBuilder.ToString();
    }

    /// <summary>
    /// Generates a SQL INSERT statement for the specified table based on the provided query options.
    /// </summary>
    /// <param name="table">The table for which the INSERT statement will be generated.</param>
    /// <param name="providerName">The name of the database provider used to format the SQL syntax.</param>
    /// <param name="options">The query options that determine which columns to include and whether to qualify the table name.</param>
    /// <returns>A string containing the generated SQL INSERT statement.</returns>
    public static string GenerateInsert(this Table table, string providerName, QueryOptions options)
    {
        StringBuilder queryBuilder = new("INSERT INTO ");
        queryBuilder.AppendNameOf(table, providerName, options).Append(" (");

        foreach (var column in table.Columns.Where(c => c.IsMatch(options)))
            queryBuilder.Append(Utility.Escape(column.Name, providerName)).Append(", ");

        queryBuilder.Length -= 2;
        queryBuilder.Append(") VALUES (");

        foreach (var column in table.Columns.Where(c => c.IsMatch(options)))
            queryBuilder.Append(Utility.ToParameterName(column.Name, providerName)).Append(", ");

        queryBuilder.Length -= 2;
        queryBuilder.Append(')');

        return queryBuilder.ToString();
    }

    /// <summary>
    /// Generates a SQL UPDATE statement for the specified table, including the columns to update and the primary key for filtering.
    /// </summary>
    /// <param name="table">The table for which the UPDATE statement will be generated.</param>
    /// <param name="providerName">The name of the database provider being used, which determines SQL syntax specifics.</param>
    /// <param name="options">The query options that define which columns to include and whether to qualify the table name.</param>
    /// <returns>A string containing the generated SQL UPDATE statement.</returns>
    public static string GenerateUpdate(this Table table, string providerName, QueryOptions options)
    {
        StringBuilder queryBuilder = new("UPDATE ");
        queryBuilder.AppendNameOf(table, providerName, options).Append(" SET ");

        foreach (var columnName in table.Columns
                                        .Where(c => !c.IsPKColumn && c.IsMatch(options))
                                        .Select(c => c.Name))
        {
            queryBuilder.Append(Utility.Escape(columnName, providerName)).Append(" = ");
            queryBuilder.Append(Utility.ToParameterName(columnName, providerName)).Append(", ");
        }

        queryBuilder.Length -= 2;
        queryBuilder.AppendFilterBy(table.PrimaryKey, providerName);

        return queryBuilder.ToString();
    }

    /// <summary>
    /// Generates a SQL DELETE statement for the specified table using the given provider and query options.
    /// </summary>
    /// <param name="table">The table for which the DELETE statement will be generated.</param>
    /// <param name="providerName">The name of the database provider, used to ensure compatibility when generating the SQL statement.</param>
    /// <param name="options">The query options that specify how the table name should be qualified and determine whether certain table features should be skipped.</param>
    /// <returns>A string containing the generated SQL DELETE statement.</returns>
    public static string GenerateDelete(this Table table, string providerName, QueryOptions options)
    {
        StringBuilder queryBuilder = new("DELETE FROM ");
        queryBuilder.AppendNameOf(table, providerName, options);
        queryBuilder.AppendFilterBy(table.PrimaryKey, providerName);

        return queryBuilder.ToString();
    }

    /// <summary>
    /// Determines whether a column matches the specified query options.
    /// </summary>
    /// <param name="c">The column to evaluate against the query options.</param>
    /// <param name="o">The query options that define the criteria for a column to match.</param>
    /// <returns>A boolean value indicating whether the column meets the specified options.</returns>
    private static bool IsMatch(this Column c, QueryOptions o) =>
        !((o.HasFlag(QueryOptions.SkipIdentity) && c.IsIdentity) ||
          (o.HasFlag(QueryOptions.SkipComputed) && c.IsComputed) ||
          (o.HasFlag(QueryOptions.SkipRowVersion) && c.ColumnType == ColumnType.RowVersion));

    /// <summary>
    /// Appends a fully qualified or unqualified table name to the provided <see cref="StringBuilder"/> instance based on the specified query options.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> instance to which the table name will be appended.</param>
    /// <param name="table">The <see cref="Table"/> whose name will be appended.</param>
    /// <param name="providerName">The name of the database provider, used to escape identifiers.</param>
    /// <param name="options">The query options that determine whether the table name should be qualified with its owner.</param>
    /// <returns>The <see cref="StringBuilder"/> instance with the appended table name.</returns>
    private static StringBuilder AppendNameOf(this StringBuilder sb, Table table, string providerName,
                                              QueryOptions options)
    {
        if (options.HasFlag(QueryOptions.QualifyTableName) && !string.IsNullOrEmpty(table.Owner))
            sb.Append(Utility.Escape(table.Owner, providerName)).Append('.');

        sb.Append(Utility.Escape(table.Name, providerName));

        return sb;
    }

    /// <summary>
    /// Appends a SQL WHERE clause to the provided StringBuilder instance using the specified key columns
    /// and provider-specific syntax for a database.
    /// </summary>
    /// <param name="sb">The StringBuilder instance to which the WHERE clause will be appended.</param>
    /// <param name="key">The key object containing the columns to be included in the filter.</param>
    /// <param name="providerName">The name of the database provider to ensure provider-specific escaping and parameter naming conventions.</param>
    /// <returns>The updated StringBuilder instance containing the appended WHERE clause.</returns>
    private static StringBuilder AppendFilterBy(this StringBuilder sb, Key key, string providerName)
    {
        sb.Append(" WHERE ");

        foreach (var columnName in key.Columns.Select(c => c.Name))
        {
            sb.Append(Utility.Escape(columnName, providerName)).Append(" = ");
            sb.Append(Utility.ToParameterName(columnName, providerName)).Append(" AND ");
        }

        sb.Length -= 5;

        return sb;
    }

    #endregion

    #region Raw data extraction/migration

    /// <summary>
    /// Opens a data reader for the specified table using the provided query options.
    /// </summary>
    /// <param name="table">The table for which the data reader will be opened.</param>
    /// <param name="options">The query options that define how the SELECT statement should be generated.</param>
    /// <returns>A <see cref="DbDataReader"/> instance to read the rows retrieved from the specified table.
    /// The connection will automatically close when the reader is disposed.</returns>
    public static DbDataReader OpenReader(this Table table, QueryOptions options)
    {
        var connection = Utility.GetConnection(table.Database);
        connection.Open();

        var command = connection.CreateCommand();
        command.CommandText = table.GenerateSelect(options);

        return command.ExecuteReader(CommandBehavior.CloseConnection);
    }

    /// <summary>
    /// Copies data from the specified table to the target database connection using the provided query options.
    /// </summary>
    /// <param name="table">The table from which data will be copied.</param>
    /// <param name="targetConnection">The target database connection where the data will be inserted.</param>
    /// <param name="sourceOptions">The query options that define how data is read from the source table.</param>
    /// <param name="targetOptions">The query options that define how data is inserted into the target database.</param>
    public static void CopyTo(this Table table, DbConnection targetConnection, QueryOptions sourceOptions,
                              QueryOptions targetOptions)
    {
        using var helper = new SqlHelper(targetConnection);
        using var sourceReader = table.OpenReader(sourceOptions);
        var insertSql = table.GenerateInsert(helper.ProviderName, targetOptions);
        helper.ExecuteBatch(insertSql, sourceReader);
    }

    #endregion

    #region Query methods

    /// <summary>
    /// Executes a SQL SELECT query on the specified table and processes the result set using the provided extractor function.
    /// </summary>
    /// <typeparam name="TRowSet">The type of the result set that will be created from the query.</typeparam>
    /// <param name="table">The table on which the SELECT query will be executed.</param>
    /// <param name="extractor">A function that processes the data reader and extracts the result set.</param>
    /// <returns>The result set created by the extractor function based on the query output.</returns>
    public static TRowSet Select<TRowSet>(this Table table, Func<DbDataReader, TRowSet> extractor)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateSelect(QueryOptions.QualifyTableName);
        return helper.Query(sql, extractor);
    }

    /// <summary>
    /// Returns a list of entities of the specified type, mapped from the rows in the table.
    /// </summary>
    /// <param name="table">The table from which data will be selected and mapped to entities.</param>
    /// <typeparam name="TRow">The type of entity to which each row in the table will be mapped. Must be a class with a parameterless constructor.</typeparam>
    /// <returns>A list of entities of the specified type, representing the data from the table.</returns>
    public static List<TRow> Select<TRow>(this Table table) where TRow : class, new() =>
        table.Select(SqlHelper.ToEntityList<TRow>);

    /// <summary>
    /// Executes a SQL SELECT query for the specified table and key and maps the result set
    /// to a custom type using the provided key binder and data extraction function.
    /// </summary>
    /// <param name="table">The table for which the SELECT query will be executed.</param>
    /// <param name="key">The key used to filter the query results.</param>
    /// <param name="keyValue">The value of the key to use with the SELECT query.</param>
    /// <param name="keyBinder">A function that binds the key value to the database command parameters.</param>
    /// <param name="extractor">A function that extracts data from the query results and maps it to the specified type.</param>
    /// <typeparam name="TRowSet">The type into which the query results will be mapped.</typeparam>
    /// <typeparam name="TKey">The type of the key value used for query filtering.</typeparam>
    /// <returns>An instance of <typeparamref name="TRowSet"/> containing the extracted query results.</returns>
    public static TRowSet Select<TRowSet, TKey>(this Table table, Key key, TKey keyValue,
                                                Action<DbCommand, TKey> keyBinder,
                                                Func<DbDataReader, TRowSet> extractor)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateSelect(key, QueryOptions.QualifyTableName);
        return helper.Query(sql, keyValue, keyBinder, extractor);
    }

    /// <summary>
    /// Retrieves a list of entities of type <typeparamref name="TRow"/> from the specified table
    /// based on the provided key and key values.
    /// </summary>
    /// <param name="table">The table from which to select rows.</param>
    /// <param name="key">The key that defines the criteria used for selection.</param>
    /// <param name="keyValues">The values of the key to be used as the selection criteria.</param>
    /// <typeparam name="TRow">The entity type of the rows to be retrieved. Must be a class with a parameterless constructor.</typeparam>
    /// <returns>A list of entities of type <typeparamref name="TRow"/> representing the selected rows.</returns>
    public static List<TRow> Select<TRow>(this Table table, Key key, params object[] keyValues)
        where TRow : class, new() =>
        table.Select(key, keyValues, SqlHelper.FromArray, SqlHelper.ToEntityList<TRow>);

    #endregion

    #region Simple update methods

    /// <summary>
    /// Inserts a new row into the specified table using the provided row value and a custom row binder action.
    /// </summary>
    /// <typeparam name="TRow">The type of the row object to be inserted.</typeparam>
    /// <param name="table">The table where the row will be inserted.</param>
    /// <param name="rowValue">The value of the row to insert.</param>
    /// <param name="rowBinder">A delegate that binds the row value to a database command.</param>
    /// <returns>A boolean indicating whether the insertion was successful.</returns>
    public static bool Insert<TRow>(this Table table, TRow rowValue, Action<DbCommand, TRow> rowBinder)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateInsert(table.Database.ProviderName, QueryOptions.All);
        return helper.Execute(sql, rowValue, rowBinder) > 0;
    }

    /// <summary>
    /// Inserts a row into the specified table using the provided row data and a default row binder.
    /// </summary>
    /// <typeparam name="TRow">The type of the row data to be inserted, which must be a class with a parameterless constructor.</typeparam>
    /// <param name="table">The table into which the row will be inserted.</param>
    /// <param name="rowValue">The data for the row to be inserted.</param>
    /// <returns>A boolean indicating whether the row was successfully inserted.</returns>
    public static bool Insert<TRow>(this Table table, TRow rowValue) where TRow : class, new() =>
        table.Insert(rowValue, SqlHelper.FromEntity);

    /// <summary>
    /// Inserts a new row into the specified table using the provided values.
    /// </summary>
    /// <param name="table">The table where the data will be inserted.</param>
    /// <param name="rowValues">An array of values representing the data for the row to be inserted.</param>
    /// <returns>A boolean value indicating whether the insert operation was successful.</returns>
    public static bool Insert(this Table table, params object[] rowValues) =>
        table.Insert(rowValues, SqlHelper.FromArray);

    /// <summary>
    /// Executes an update operation on the specified table using the given row value and a binding action to populate parameter values.
    /// </summary>
    /// <param name="table">The table on which the update operation will be executed.</param>
    /// <param name="rowValue">The row data containing the values to be updated.</param>
    /// <param name="rowBinder">An action that binds the provided row data to the parameters of the database command.</param>
    /// <typeparam name="TRow">The type of the row value being updated.</typeparam>
    /// <returns>A boolean value indicating whether the update operation affected one or more rows.</returns>
    public static bool Update<TRow>(this Table table, TRow rowValue, Action<DbCommand, TRow> rowBinder)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateUpdate(table.Database.ProviderName, QueryOptions.All);
        return helper.Execute(sql, rowValue, rowBinder) > 0;
    }

    /// <summary>
    /// Updates the specified table with the provided row data.
    /// </summary>
    /// <typeparam name="TRow">The type of the row data. Must be a reference type with a parameterless constructor.</typeparam>
    /// <param name="table">The table to be updated.</param>
    /// <param name="rowValue">The object containing the data to update the table with.</param>
    /// <returns>A boolean indicating whether the update operation was successful.</returns>
    public static bool Update<TRow>(this Table table, TRow rowValue) where TRow : class, new() =>
        table.Update(rowValue, SqlHelper.FromEntity);

    /// <summary>
    /// Deletes a record from the specified table based on the provided key value and binds the key using the given key binder.
    /// </summary>
    /// <typeparam name="TKey">The type of the key used to identify the record to delete.</typeparam>
    /// <param name="table">The table from which the record will be deleted.</param>
    /// <param name="keyValue">The key value identifying the record to delete.</param>
    /// <param name="keyBinder">A delegate that binds the key value to a database command.</param>
    /// <returns>A boolean indicating whether the record was successfully deleted.</returns>
    public static bool Delete<TKey>(this Table table, TKey keyValue, Action<DbCommand, TKey> keyBinder)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateDelete(table.Database.ProviderName, QueryOptions.QualifyTableName);
        return helper.Execute(sql, keyValue, keyBinder) > 0;
    }

    /// <summary>
    /// Deletes a record from the specified table using the provided key value and binds the key to the using a default key binder.
    /// </summary>
    /// <typeparam name="TKey">The type of the key value used to identify the record to delete.</typeparam>
    /// <param name="table">The table from which the record will be deleted.</param>
    /// <param name="keyValue">The key value of the record to be deleted.</param>
    /// <returns>A boolean value indicating whether the deletion was successful.</returns>
    public static bool Delete<TKey>(this Table table, TKey keyValue) where TKey : class, new() =>
        table.Delete(keyValue, SqlHelper.FromEntity);

    /// <summary>
    /// Deletes a row from the specified table using the provided key values to identify the target row.
    /// </summary>
    /// <param name="table">The table from which the row will be deleted.</param>
    /// <param name="keyValues">An array of key values used to locate the row to delete.</param>
    /// <returns>A boolean value indicating whether the deletion was successful.</returns>
    public static bool Delete(this Table table, params object[] keyValues) =>
        table.Delete(keyValues, SqlHelper.FromArray);

    #endregion

    #region Batch update methods

    /// <summary>
    /// Inserts a batch of rows into the specified table using the provided binding logic to map rows to database parameters.
    /// </summary>
    /// <typeparam name="TRow">The type of the data rows to be inserted.</typeparam>
    /// <param name="table">The target table into which the rows will be inserted.</param>
    /// <param name="rowValues">The collection of data rows to insert into the table.</param>
    /// <param name="rowBinder">The callback function responsible for binding each row to the database command parameters.</param>
    /// <returns>A boolean value indicating whether the batch insert operation affected any rows.</returns>
    public static bool InsertBatch<TRow>(this Table table, IEnumerable<TRow> rowValues,
                                         Action<DbCommand, TRow> rowBinder)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateInsert(table.Database.ProviderName, QueryOptions.All);
        return helper.ExecuteBatch(sql, rowValues, rowBinder) > 0;
    }

    /// <summary>
    /// Inserts a batch of rows into the specified table using the provided row values and a default row binding implementation.
    /// </summary>
    /// <typeparam name="TRow">The type of the rows being inserted. Must be a class and have a parameterless constructor.</typeparam>
    /// <param name="table">The table into which the rows will be inserted.</param>
    /// <param name="rowValues">The collection of row values to be inserted into the table.</param>
    /// <returns>True if the batch insert operation succeeds; otherwise, false.</returns>
    public static bool InsertBatch<TRow>(this Table table, IEnumerable<TRow> rowValues) where TRow : class, new() =>
        table.InsertBatch(rowValues, SqlHelper.FromEntity);

    /// <summary>
    /// Updates a batch of rows in the specified table using the provided row values and a function to bind parameter values to the command.
    /// </summary>
    /// <typeparam name="TRow">The type of the objects representing the rows to be updated.</typeparam>
    /// <param name="table">The table where the rows will be updated.</param>
    /// <param name="rowValues">The collection of row values to update the table with.</param>
    /// <param name="rowBinder">The function that binds parameter values to the database command object for each row.</param>
    /// <returns>A boolean value indicating whether the batch update affected any rows.</returns>
    public static bool UpdateBatch<TRow>(this Table table, IEnumerable<TRow> rowValues,
                                         Action<DbCommand, TRow> rowBinder)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateUpdate(table.Database.ProviderName, QueryOptions.All);
        return helper.ExecuteBatch(sql, rowValues, rowBinder) > 0;
    }

    /// <summary>
    /// Updates a batch of rows in the specified table using the provided collection of row values and a default entity-to-command binder.
    /// </summary>
    /// <typeparam name="TRow">The type of the rows in the collection, which must be a reference type with a parameterless constructor.</typeparam>
    /// <param name="table">The table where the batch update will be applied.</param>
    /// <param name="rowValues">The collection of row values to be updated in the table.</param>
    /// <returns>True if the batch update is successful; otherwise, false.</returns>
    public static bool UpdateBatch<TRow>(this Table table, IEnumerable<TRow> rowValues) where TRow : class, new() =>
        table.UpdateBatch(rowValues, SqlHelper.FromEntity);

    /// <summary>
    /// Executes a batch delete operation for the specified table based on a collection of key values.
    /// </summary>
    /// <typeparam name="TKey">The type of the key values used to identify the records to delete.</typeparam>
    /// <param name="table">The table from which records will be deleted.</param>
    /// <param name="keyValues">The collection of key values representing the records to delete.</param>
    /// <param name="keyBinder">
    /// A callback action to bind the key value to the database command parameters.
    /// </param>
    /// <returns>A boolean value indicating whether the operation affected any records.</returns>
    public static bool DeleteBatch<TKey>(this Table table, IEnumerable<TKey> keyValues,
                                         Action<DbCommand, TKey> keyBinder)
    {
        using var helper = new SqlHelper(table.Database);
        var sql = table.GenerateDelete(table.Database.ProviderName, QueryOptions.QualifyTableName);
        return helper.ExecuteBatch(sql, keyValues, keyBinder) > 0;
    }

    /// <summary>
    /// Deletes a batch of records from the specified table based on the provided key values.
    /// </summary>
    /// <typeparam name="TKey">The type of the key used to identify records for deletion.</typeparam>
    /// <param name="table">The table from which the records will be deleted.</param>
    /// <param name="keyValues">A collection of key values identifying the records to be deleted.</param>
    /// <returns>A boolean indicating whether the operation was successful.</returns>
    public static bool DeleteBatch<TKey>(this Table table, IEnumerable<TKey> keyValues) where TKey : class, new() =>
        table.DeleteBatch(keyValues, SqlHelper.FromEntity);

    #endregion
}
